### PR TITLE
Adding TimeScale Datasource

### LINKED ISSUE #1668: Add TimeScale as a supported datasource :timer_clock: :electric_plug:
We need to increase the number of datasources that MindsDB supports. This task should add a new datasource for connecting to TimeScale DB. You can get more info on [TimeScale](https://docs.timescale.com/) docs. Since TimeScale is PostgreSQL extension you can reuse/extend the [PostgreSQL](https://github.com/mindsdb/datasources/blob/staging/mindsdb_datasources/datasources/postgres_ds.py#L9) datasource.
If possible, please include a test for the datasource. You can check the example [here](https://github.com/mindsdb/datasources/tree/staging/tests).

>Note: if you are familiar with another datasource that MindsDB doesn't support, feel free to work on that and make a PR.

## Steps :male_detective: :female_detective: 

- [ ] Frok datasources repo
- [ ] Add new datasource file in https://github.com/mindsdb/datasources/tree/staging/mindsdb_datasources/datasources
- [ ] Add test(optional)
- [ ] Make a PR to staging branch

## Additional rewards :1st_place_medal: 

Each datasource PR brings  :four:  point for entry into the draw for a :computer:  Deep Learning Laptop powered by the NVIDIA RTX 3080 Max-Q GPU or other swag :shirt: :bear: .  For more info check out https://mindsdb.com/hacktoberfest/

### PR DESCRIPTION
**Pull request by MichaelLantz**
Fixes mindsdb/mindsdb#1668

## Please describe what changes you made, in as much detail as possible
  - Adding datasource for TimeScale
  - Adding test against TimeScale datasource
  - Adding initialization check for TimeScale datasource

mindsdb

### CODE REVIEW

**Comment by MichaelLantz** [comment]
For the life of me I can't figure out how to get my local test set up correctly. I've been digging through documentation and yml builds that setup DATABASE_CREDENTIALS and other per-requisites needed for a successful test run.

I end up with a stack trace like this:

ERROR: test_postgres_ds (unittest.loader._FailedTest)
`
ImportError: Failed to import test module: test_postgres_ds
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/michael/Documents/GitHub/datasources/tests/test_postgres_ds.py", line 3, in <module>
    from common import DB_CREDENTIALS, break_dataset
  File "/home/michael/Documents/GitHub/datasources/tests/common.py", line 12, in <module>
    with open(os.path.join(os.path.expanduser("~"), '.mindsdb_credentials.json'), 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/michael/.mindsdb_credentials.json'
`
I think this can be resolved by following [these steps](https://github.com/mindsdb/mindsdb/blob/staging/tests/README.md), however I don't know what the contents of these json files should look like. The json configs [here](https://docs.mindsdb.com/datasources/configuration/#postgresql-configuration) are different and I don't think are meant for this but maybe I'm missing something simple.

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
This was already resolved, but we can re use the test. Can you please just add the test in this PR?

**Comment by MichaelLantz** [comment]
No worries! I'll have those changes in a jiffy.

**Comment by MichaelLantz** [comment]
Hi @ZoranPandovski,

I refactored the files that had conflicts using the changes merged from the other Timescale code changes that were merged. I think doing this will help resolve the merge conflict on this PR but I think I may be missing access to resolve. If that doesn't work maybe I'll just create a separate pull request with only the test. Hope this helps.

**Comment by ZoranPandovski** [comment]
If it is easier for you sure. Let's have another PR. Thanks

**Comment by MichaelLantz** [comment]
Closing and will re-create separate pull request.

**Comment by MichaelLantz** [comment]
Hi again @ZoranPandovski. I added a separate request in https://github.com/mindsdb/datasources/pull/44.

**Pull request closed without merging**
