### PR TITLE
Adding CrateDb as a data source

### PR DESCRIPTION
**Pull request by abhishekpcnair**
I have added CrateDB as a data source. This is my first PR, I hope I didn't miss out on anything.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement]() before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by abhishekpcnair** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Thanks, can you please add the `crate` requirements to optional_requirements_extra_data_sources

**Comment by abhishekpcnair** [comment]
@ZoranPandovski I have added the dependency!

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
