### PR TITLE
oracle datasource added first commit check

### PR DESCRIPTION
**Pull request by ath34-tech**
I added a data source for oracle here, I used PostgreSQL and MySQL data source for reference. I checked it on some local data and got the expected results. will be happy to share them.

### CODE REVIEW

**Review by ZoranPandovski — APPROVED** [review]
Thanks @ath34-tech

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
****CLA Assistant Lite bot**** All contributors have signed the CLA  ✍️ ✅

**Comment by ath34-tech** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ath34-tech** [comment]
recheckcla

**Comment by ath34-tech** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Comment by ath34-tech** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Pull request merged**
